image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose up -d
  - sudo apt-get -qq update
  - sudo apt-get install wait-for-it > /dev/null

build_script:
  - java -jar db-api.jar &
  - wait-for-it localhost:9999 -t 100
  - curl --show-error -X GET 'http://localhost:9999/api/cards'
